name: Full Build Workflow

on:
  workflow_dispatch:  # Запуск вручную

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install AppImage dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 libfuse-dev build-essential

      - name: Gradle Build Ubuntu
        run: |
          ./gradlew packageDeb
          ./gradlew packageAppImage
          ./gradlew packageJar
          ./gradlew assembleRelease

  build-fedora:
    name: Build on Fedora
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
      - name: Install dependencies
        run: |
          dnf install -y java-21-openjdk-devel unzip git
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Gradle Build Fedora
        run: ./gradlew packageRmp

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle Build Windows
        run: |
          ./gradlew packageMsi
          ./gradlew packageExe

  build-macos:
    name: Build on macOS
    runs-on: macos-14 # macos-14 поддерживает Xcode 15 по умолчанию

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle Build macOS
        run: |
          ./gradlew packageDmg
          ./gradlew packagePkg
          ./gradlew linkReleaseFrameworkIosX64 \
                     linkReleaseFrameworkIosSimulatorArm64 \
                     linkReleaseFrameworkIosArm64

      - name: Build Xcode project
        run: |
          xcodebuild -project YourXcodeProject.xcodeproj \
                     -scheme YourScheme \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     clean build
