name: Full Release Build Workflow

on:
  workflow_dispatch:

jobs:

  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install AppImage tools and SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y appstream-util libfuse2 libfuse-dev default-jdk

      - name: Build DEB package
        run: ./gradlew packageReleaseDeb

      - name: Build AppImage
        run: ./gradlew packageReleaseAppImage

      - name: Build JAR
        run: ./gradlew packageReleaseJar

      - name: Assemble release
        run: ./gradlew assembleRelease

  build-fedora:
    name: Build on Fedora
    runs-on: ubuntu-latest # Emulate Fedora using container
    container: fedora:latest
    steps:
      - name: Install dependencies
        run: |
          dnf install -y java-21-openjdk-devel git make

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build RPM package
        run: ./gradlew packageReleaseRmp

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build MSI
        run: ./gradlew packageReleaseMsi

      - name: Build EXE
        run: ./gradlew packageReleaseExe

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build DMG
        run: ./gradlew packageReleaseDmg

      - name: Build PKG
        run: ./gradlew packageReleasePkg

      - name: Link iOS frameworks
        run: ./gradlew linkReleaseFrameworkIosX64 linkReleaseFrameworkIosSimulatorArm64 linkReleaseFrameworkIosArm64

      - name: Build Xcode project
        run: |
          xcodebuild -project YourXcodeProject.xcodeproj \
                     -scheme YourScheme \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     clean build
