name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ipa:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build XCFramework
        run: ./gradlew assembleReleaseXCFramework

      - name: Copy XCFramework to Xcode project
        run: |
          mkdir -p iosApp/Frameworks
          cp -R build/XCFrameworks/release/*.xcframework iosApp/Frameworks/

      - name: Build IPA
        run: |
          xcodebuild \
            -project iosApp.xcodeproj \
            -scheme "LevelUp-Soul" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ${{ github.workspace }}/build/iosApp.xcarchive \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath ${{ github.workspace }}/build/iosApp.xcarchive \
            -exportOptionsPlist iosApp/ExportOptions.plist \
            -exportPath ${{ github.workspace }}/build/ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ipa/*.ipa
