name: Android&Ubuntu build

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install dependencies for AppImage
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2 appstream jq

    - name: Grant execution permission to Gradlew
      run: chmod +x ./gradlew

    - name: Build DEB package
      run: ./gradlew packageReleaseDeb

    - name: Build AppImage
      run: ./gradlew packageReleaseAppImage

    - name: Build JAR
      run: ./gradlew packageReleaseJar

    - name: Assemble Release
      run: ./gradlew assembleRelease

    - name: Prepare release folder
      run: |
        mkdir -p release/latest
        find composeApp/build/ -type f \( -iname '*.deb' -o -iname '*.AppImage' -o -iname '*.jar' -iname '*.apk'\) -exec cp {} release/latest/ \;

    - name: Commit release artifacts
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add release/latest/*
        git commit -m "ci: update release/latest with new release packages [skip ci]" || echo "No changes to commit"
        git push origin HEAD:main
