name: Windows Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build MSI
        run: ./gradlew packageReleaseMsi

      - name: Build EXE
        run: ./gradlew packageReleaseExe

      - name: Build JAR
        run: ./gradlew packageReleaseJar

      - name: Prepare release folder
        run: |
          mkdir release\latest
          powershell -Command "Get-ChildItem -Path 'composeApp\build\' -Recurse -Include '*.msi','*.exe','*.jar' | Copy-Item -Destination 'release\latest\' -Force"
        shell: powershell

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-packages-windows
          path: |
            composeApp\build\**\*.msi
            composeApp\build\**\*.exe
            composeApp\build\**\*.jar
